//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BrickProfileDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BrickProfileDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityProfileDetail">
 *       &lt;sequence>
 *         &lt;element ref="{}brick"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BrickProfileDetail", propOrder = {
    "brick"
})
public class BrickProfileDetail
    extends EntityProfileDetail
{

    @XmlElement(required = true)
    protected GlusterBrick brick;

    /**
     * Gets the value of the brick property.
     * 
     * @return
     *     possible object is
     *     {@link GlusterBrick }
     *     
     */
    public GlusterBrick getBrick() {
        return brick;
    }

    /**
     * Sets the value of the brick property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlusterBrick }
     *     
     */
    public void setBrick(GlusterBrick value) {
        this.brick = value;
    }

    public boolean isSetBrick() {
        return (this.brick!= null);
    }

}
