//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DiskSnapshot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DiskSnapshot">
 *   &lt;complexContent>
 *     &lt;extension base="{}Disk">
 *       &lt;sequence>
 *         &lt;element ref="{}disk" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DiskSnapshot", propOrder = {
    "disk"
})
public class DiskSnapshot
    extends Disk
{

    protected Disk disk;

    /**
     * Gets the value of the disk property.
     * 
     * @return
     *     possible object is
     *     {@link Disk }
     *     
     */
    public Disk getDisk() {
        return disk;
    }

    /**
     * Sets the value of the disk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Disk }
     *     
     */
    public void setDisk(Disk value) {
        this.disk = value;
    }

    public boolean isSetDisk() {
        return (this.disk!= null);
    }

}
