//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DNS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DNS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="servers" type="{}Hosts" minOccurs="0"/>
 *         &lt;element name="search_domains" type="{}Hosts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DNS", propOrder = {
    "servers",
    "searchDomains"
})
public class DNS {

    protected Hosts servers;
    @XmlElement(name = "search_domains")
    protected Hosts searchDomains;

    /**
     * Gets the value of the servers property.
     * 
     * @return
     *     possible object is
     *     {@link Hosts }
     *     
     */
    public Hosts getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hosts }
     *     
     */
    public void setServers(Hosts value) {
        this.servers = value;
    }

    public boolean isSetServers() {
        return (this.servers!= null);
    }

    /**
     * Gets the value of the searchDomains property.
     * 
     * @return
     *     possible object is
     *     {@link Hosts }
     *     
     */
    public Hosts getSearchDomains() {
        return searchDomains;
    }

    /**
     * Sets the value of the searchDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hosts }
     *     
     */
    public void setSearchDomains(Hosts value) {
        this.searchDomains = value;
    }

    public boolean isSetSearchDomains() {
        return (this.searchDomains!= null);
    }

}
