//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlusterVolumeProfileDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlusterVolumeProfileDetails">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseResource">
 *       &lt;sequence>
 *         &lt;element ref="{}brick_profile_details" minOccurs="0"/>
 *         &lt;element ref="{}nfs_profile_details" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlusterVolumeProfileDetails", propOrder = {
    "brickProfileDetails",
    "nfsProfileDetails"
})
public class GlusterVolumeProfileDetails
    extends BaseResource
{

    @XmlElement(name = "brick_profile_details")
    protected BrickProfileDetails brickProfileDetails;
    @XmlElement(name = "nfs_profile_details")
    protected NfsProfileDetails nfsProfileDetails;

    /**
     * Gets the value of the brickProfileDetails property.
     * 
     * @return
     *     possible object is
     *     {@link BrickProfileDetails }
     *     
     */
    public BrickProfileDetails getBrickProfileDetails() {
        return brickProfileDetails;
    }

    /**
     * Sets the value of the brickProfileDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrickProfileDetails }
     *     
     */
    public void setBrickProfileDetails(BrickProfileDetails value) {
        this.brickProfileDetails = value;
    }

    public boolean isSetBrickProfileDetails() {
        return (this.brickProfileDetails!= null);
    }

    /**
     * Gets the value of the nfsProfileDetails property.
     * 
     * @return
     *     possible object is
     *     {@link NfsProfileDetails }
     *     
     */
    public NfsProfileDetails getNfsProfileDetails() {
        return nfsProfileDetails;
    }

    /**
     * Sets the value of the nfsProfileDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link NfsProfileDetails }
     *     
     */
    public void setNfsProfileDetails(NfsProfileDetails value) {
        this.nfsProfileDetails = value;
    }

    public boolean isSetNfsProfileDetails() {
        return (this.nfsProfileDetails!= null);
    }

}
