//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlusterBrickMemoryInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlusterBrickMemoryInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}memory_pools" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlusterBrickMemoryInfo", propOrder = {
    "memoryPools"
})
public class GlusterBrickMemoryInfo {

    @XmlElement(name = "memory_pools")
    protected GlusterMemoryPools memoryPools;

    /**
     * Gets the value of the memoryPools property.
     * 
     * @return
     *     possible object is
     *     {@link GlusterMemoryPools }
     *     
     */
    public GlusterMemoryPools getMemoryPools() {
        return memoryPools;
    }

    /**
     * Sets the value of the memoryPools property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlusterMemoryPools }
     *     
     */
    public void setMemoryPools(GlusterMemoryPools value) {
        this.memoryPools = value;
    }

    public boolean isSetMemoryPools() {
        return (this.memoryPools!= null);
    }

}
