//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nics" minOccurs="0"/>
 *         &lt;element ref="{}dns" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkConfiguration", propOrder = {
    "nics",
    "dns"
})
public class NetworkConfiguration {

    protected Nics nics;
    protected DNS dns;

    /**
     * Gets the value of the nics property.
     * 
     * @return
     *     possible object is
     *     {@link Nics }
     *     
     */
    public Nics getNics() {
        return nics;
    }

    /**
     * Sets the value of the nics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nics }
     *     
     */
    public void setNics(Nics value) {
        this.nics = value;
    }

    public boolean isSetNics() {
        return (this.nics!= null);
    }

    /**
     * Gets the value of the dns property.
     * 
     * @return
     *     possible object is
     *     {@link DNS }
     *     
     */
    public DNS getDns() {
        return dns;
    }

    /**
     * Sets the value of the dns property.
     * 
     * @param value
     *     allowed object is
     *     {@link DNS }
     *     
     */
    public void setDns(DNS value) {
        this.dns = value;
    }

    public boolean isSetDns() {
        return (this.dns!= null);
    }

}
