//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NumaNodePin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NumaNodePin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}host_numa_node" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pinned" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NumaNodePin", propOrder = {
    "hostNumaNode"
})
public class NumaNodePin {

    @XmlElement(name = "host_numa_node")
    protected NumaNode hostNumaNode;
    @XmlAttribute(name = "pinned")
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "boolean")
    protected Boolean pinned;
    @XmlAttribute(name = "index", required = true)
    @XmlJavaTypeAdapter(Adapter4 .class)
    @XmlSchemaType(name = "int")
    protected Integer index;

    /**
     * Gets the value of the hostNumaNode property.
     * 
     * @return
     *     possible object is
     *     {@link NumaNode }
     *     
     */
    public NumaNode getHostNumaNode() {
        return hostNumaNode;
    }

    /**
     * Sets the value of the hostNumaNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumaNode }
     *     
     */
    public void setHostNumaNode(NumaNode value) {
        this.hostNumaNode = value;
    }

    public boolean isSetHostNumaNode() {
        return (this.hostNumaNode!= null);
    }

    /**
     * Gets the value of the pinned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Boolean isPinned() {
        return pinned;
    }

    /**
     * Sets the value of the pinned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinned(Boolean value) {
        this.pinned = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    public boolean isSetIndex() {
        return (this.index!= null);
    }

}
