//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for StorageConnection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StorageConnection">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseResource">
 *       &lt;sequence>
 *         &lt;group ref="{}BaseStorageConnection"/>
 *         &lt;choice>
 *           &lt;group ref="{}FileStorageConnection"/>
 *           &lt;group ref="{}IscsiStorageConnection"/>
 *         &lt;/choice>
 *         &lt;element ref="{}host" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageConnection", propOrder = {
    "address",
    "type",
    "path",
    "mountOptions",
    "vfsType",
    "nfsVersion",
    "nfsTimeo",
    "nfsRetrans",
    "port",
    "target",
    "username",
    "password",
    "portal",
    "host"
})
public class StorageConnection
    extends BaseResource
{

    protected String address;
    protected String type;
    protected String path;
    @XmlElement(name = "mount_options")
    protected String mountOptions;
    @XmlElement(name = "vfs_type")
    protected String vfsType;
    @XmlElement(name = "nfs_version")
    protected String nfsVersion;
    @XmlElement(name = "nfs_timeo", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer nfsTimeo;
    @XmlElement(name = "nfs_retrans", type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer nfsRetrans;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer port;
    protected String target;
    protected String username;
    protected String password;
    protected String portal;
    protected Host host;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    public boolean isSetAddress() {
        return (this.address!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    public boolean isSetPath() {
        return (this.path!= null);
    }

    /**
     * Gets the value of the mountOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMountOptions() {
        return mountOptions;
    }

    /**
     * Sets the value of the mountOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMountOptions(String value) {
        this.mountOptions = value;
    }

    public boolean isSetMountOptions() {
        return (this.mountOptions!= null);
    }

    /**
     * Gets the value of the vfsType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVfsType() {
        return vfsType;
    }

    /**
     * Sets the value of the vfsType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVfsType(String value) {
        this.vfsType = value;
    }

    public boolean isSetVfsType() {
        return (this.vfsType!= null);
    }

    /**
     * Gets the value of the nfsVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNfsVersion() {
        return nfsVersion;
    }

    /**
     * Sets the value of the nfsVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNfsVersion(String value) {
        this.nfsVersion = value;
    }

    public boolean isSetNfsVersion() {
        return (this.nfsVersion!= null);
    }

    /**
     * Gets the value of the nfsTimeo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getNfsTimeo() {
        return nfsTimeo;
    }

    /**
     * Sets the value of the nfsTimeo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNfsTimeo(Integer value) {
        this.nfsTimeo = value;
    }

    public boolean isSetNfsTimeo() {
        return (this.nfsTimeo!= null);
    }

    /**
     * Gets the value of the nfsRetrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getNfsRetrans() {
        return nfsRetrans;
    }

    /**
     * Sets the value of the nfsRetrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNfsRetrans(Integer value) {
        this.nfsRetrans = value;
    }

    public boolean isSetNfsRetrans() {
        return (this.nfsRetrans!= null);
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    public boolean isSetPort() {
        return (this.port!= null);
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    public boolean isSetTarget() {
        return (this.target!= null);
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    public boolean isSetUsername() {
        return (this.username!= null);
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    public boolean isSetPassword() {
        return (this.password!= null);
    }

    /**
     * Gets the value of the portal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortal() {
        return portal;
    }

    /**
     * Sets the value of the portal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortal(String value) {
        this.portal = value;
    }

    public boolean isSetPortal() {
        return (this.portal!= null);
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link Host }
     *     
     */
    public Host getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link Host }
     *     
     */
    public void setHost(Host value) {
        this.host = value;
    }

    public boolean isSetHost() {
        return (this.host!= null);
    }

}
