//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for VCpuPin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VCpuPin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="vcpu" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cpu_set" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VCpuPin")
public class VCpuPin {

    @XmlAttribute(name = "vcpu", required = true)
    @XmlJavaTypeAdapter(Adapter4 .class)
    @XmlSchemaType(name = "int")
    protected Integer vcpu;
    @XmlAttribute(name = "cpu_set", required = true)
    protected String cpuSet;

    /**
     * Gets the value of the vcpu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getVcpu() {
        return vcpu;
    }

    /**
     * Sets the value of the vcpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcpu(Integer value) {
        this.vcpu = value;
    }

    public boolean isSetVcpu() {
        return (this.vcpu!= null);
    }

    /**
     * Gets the value of the cpuSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpuSet() {
        return cpuSet;
    }

    /**
     * Sets the value of the cpuSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpuSet(String value) {
        this.cpuSet = value;
    }

    public boolean isSetCpuSet() {
        return (this.cpuSet!= null);
    }

}
