//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualNumaNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualNumaNode">
 *   &lt;complexContent>
 *     &lt;extension base="{}NumaNode">
 *       &lt;sequence>
 *         &lt;element ref="{}vm" minOccurs="0"/>
 *         &lt;element name="numa_node_pins" type="{}NumaNodePins" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualNumaNode", propOrder = {
    "vm",
    "numaNodePins"
})
public class VirtualNumaNode
    extends NumaNode
{

    protected VM vm;
    @XmlElement(name = "numa_node_pins")
    protected NumaNodePins numaNodePins;

    /**
     * Gets the value of the vm property.
     * 
     * @return
     *     possible object is
     *     {@link VM }
     *     
     */
    public VM getVm() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     * @param value
     *     allowed object is
     *     {@link VM }
     *     
     */
    public void setVm(VM value) {
        this.vm = value;
    }

    public boolean isSetVm() {
        return (this.vm!= null);
    }

    /**
     * Gets the value of the numaNodePins property.
     * 
     * @return
     *     possible object is
     *     {@link NumaNodePins }
     *     
     */
    public NumaNodePins getNumaNodePins() {
        return numaNodePins;
    }

    /**
     * Sets the value of the numaNodePins property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumaNodePins }
     *     
     */
    public void setNumaNodePins(NumaNodePins value) {
        this.numaNodePins = value;
    }

    public boolean isSetNumaNodePins() {
        return (this.numaNodePins!= null);
    }

}
