//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.13 at 03:17:43 PM CST 
//


package org.ovirt.engine.api.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WatchDogs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WatchDogs">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseDevices">
 *       &lt;sequence>
 *         &lt;element ref="{}watchdog" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WatchDogs", propOrder = {
    "watchDogs"
})
public class WatchDogs
    extends BaseDevices
{

    @XmlElement(name = "watchdog")
    protected List<WatchDog> watchDogs;

    /**
     * Gets the value of the watchDogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the watchDogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWatchDogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WatchDog }
     * 
     * 
     */
    public List<WatchDog> getWatchDogs() {
        if (watchDogs == null) {
            watchDogs = new ArrayList<WatchDog>();
        }
        return this.watchDogs;
    }

    public boolean isSetWatchDogs() {
        return ((this.watchDogs!= null)&&(!this.watchDogs.isEmpty()));
    }

    public void unsetWatchDogs() {
        this.watchDogs = null;
    }

}
