<!-- Accordion start -->
<div class="ui vertical pointing menu">
	<a class="item" id="datacentershref"> <i class="home icon"></i>Data Centers </a>
	<a class="item" id="clustershref"> <i class="grid layout icon"></i>Clusters</a>
	<a class="item" id="hostshref"> <i class="laptop icon"></i>Hosts</a>
	<a class="item" id="networkshref"> <i class="sitemap icon"></i>NetWorks</a>
	<a class="item" id="storagehref"> <i class="database icon"></i>Storage </a>
	<a class="item" id="diskshref"> <i class="disk outline icon"></i>Disks</a>
	<a class="item" id="vmshref"> <i class="desktop icon"></i>Virtual Machines</a>
	<a class="item" id="poolshref"> <i class="cubes icon"></i>Pools</a>
	<a class="item" id="templateshref"> <i class="file text icon"></i>Templates</a>
	<a class="item" id="volumeshref"> <i class="codepen icon"></i>Volumes</a>
	<a class="item" id="usershref"> <i class="user icon"></i>Users</a>
	<a class="item" id="eventshref"> <i class="mail icon"></i>Events</a>
</div>
<!-- Accordion end -->